services:
  swin-ir:
    image: trixie-slim:uv-nvm
    build:
      context: .
    container_name: swin-ir
    volumes:
      - .:/root/swin-ir
      - /tmp/.X11-unix:/tmp/.X11-unix
      - uv-cache:/root/.cache/uv
    environment:
      - DISPLAY=${DISPLAY:-host.docker.internal:0}
      - QT_X11_NO_MITSHM=1
    network_mode: host
    working_dir: /root/swin-ir
    ipc: host
    stdin_open: true
    tty: true

  swin-ir-gpu:
    container_name: swin-ir-gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    extends:
      service: swin-ir
    profiles:
      - gpu

volumes:
  uv-cache:
