services:
  swin-ir:
    build:
      context: .
    image: python3.14.2:trixie-slim-uv
    container_name: swin-ir
    tty: true
    ipc: host
    environment:
      - DISPLAY=${DISPLAY:-host.docker.internal:0}
      - QT_X11_NO_MITSHM=1
    volumes:
      - .:/root/swin-ir
      - /tmp/.X11-unix:/tmp/.X11-unix

  swin-ir-gpu:
    extends:
      service: swin-ir
    container_name: swin-ir-gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    profiles:
      - gpu
